//
//  Clients.ts
//
//  Generated by Poll Castillo on 15/02/2023
//
import { deleteEntity, getEntityData, registerEntity, setPassword, updateEntity, sendMail, getFilterEntityData, getFilterEntityCount } from "../../endpoints.js"
import { drawTagsIntoTables, inputObserver, inputSelect, CloseDialog, filterDataByHeaderType, getVerifyEmail, pageNumbers, fillBtnPagination, userPermissions, currentDateTime, eventLog } from "../../tools.js"
import { Data, InterfaceElement } from "../../types.js"
import { Config } from "../../Configs.js"
import { UIConvertToSU, tableLayout } from "./Layout.js"
import { tableLayoutTemplate } from "./Templates.js"
import { exportClientCsv, exportClientPdf, exportClientXls } from "../../exportFiles/clients.js"

const tableRows = Config.tableRows
const currentPage = Config.currentPage
const businessId = localStorage.getItem('business_id')
let currentWeaponInfo : any
let infoPage = {
    count: 0,
    offset: Config.offset,
    currentPage: currentPage,
    search: ""
}
let dataPage: any
const getCrews = async (): Promise<void> => {
    //const users: Data = await getEntitiesData('Crew')
    //const FSuper: Data = users.filter((data: any) => data.isSuper === false)
    //const FWeapon: Data = FSuper.filter((data: any) => `${data.customer?.id}` === `${customerId}`)
    //const data: Data = FWeapon.filter((data: any) => `${data.userType}`.includes('CUSTOMER'))
    let raw = JSON.stringify({
        "filter": {
            "conditions": [
              {
                "property": "business.id",
                "operator": "=",
                "value": `${businessId}`
              }
            ],
            
        }, 
        sort: "-createdDate",
        limit: Config.tableRows,
        offset: infoPage.offset,
        fetchPlan: 'full',
        
    })
    if(infoPage.search != ""){
        raw = JSON.stringify({
            "filter": {
                "conditions": [
                  {
                    "group": "OR",
                    "conditions": [
                      {
                        "property": "name",
                        "operator": "contains",
                        "value": `${infoPage.search.toLowerCase()}`
                      }
                    ]
                  },
                  {
                    "property": "business.id",
                    "operator": "=",
                    "value": `${businessId}`
                  }
                ]
              },
            sort: "-createdDate",
            limit: Config.tableRows,
            offset: infoPage.offset,
            fetchPlan: 'full',
            
        })
    }
    infoPage.count = await getFilterEntityCount("Crew", raw)
    dataPage = await getFilterEntityData("Crew", raw)
    return dataPage
}

export class Crews {
    private readonly dialogContainer: InterfaceElement =
        document.getElementById('app-dialogs')

    private readonly entityDialogContainer: InterfaceElement =
        document.getElementById('entity-editor-container')

    private readonly datatableContainer: InterfaceElement =
        document.getElementById('datatable-container')

    public async render(offset: any, actualPage: any, search: any): Promise<void> {
        infoPage.offset = offset
        infoPage.currentPage = actualPage
        infoPage.search = search
        this.datatableContainer.innerHTML = ''
        this.datatableContainer.innerHTML = tableLayout
        const tableBody: InterfaceElement = document.getElementById('datatable-body')
        tableBody.innerHTML = '.Cargando...'

        let data: any = await getCrews()
        tableBody.innerHTML = tableLayoutTemplate.repeat(tableRows)
        this.load(tableBody, currentPage, data)

        this.searchEntity(tableBody/*, data*/)
        new filterDataByHeaderType().filter()
        this.pagination(data, tableRows, infoPage.currentPage)
    }

    private load(table: InterfaceElement, currentPage: number, data: Data) {
        table.innerHTML = ''
        currentPage--
        let start: number = tableRows * currentPage
        let end: number = start + tableRows
        let paginatedItems: any = data.slice(start, end)

        if (data.length === 0) {
            let row: InterfaceElement = document.createElement('tr')
            row.innerHTML = `
                <td>No hay datos</td>
                <td></td>
                <td></td>
            `
            table.appendChild(row)
        }
        else {
            for (let i = 0; i < paginatedItems.length; i++) {
                let client = paginatedItems[i]
                let row: InterfaceElement =
                    document.createElement('tr')
                row.innerHTML += `
                    <td>${client.name}</dt>
                    <td>${client?.vehicular?.type ?? ''} [${client?.vehicular.licensePlate ?? ''}]</dt>
                    <td>${client?.category ?? ''}</dt>
                    <td class="tag"><span>${client?.crewState.name ?? ''}</span></td>
                    <td class="entity_options">
                        <button class="button" id="edit-entity" data-entityId="${client.id}">
                            <i class="fa-solid fa-pen"></i>
                        </button>

                        <button class="button" id="remove-entity" data-entityId="${client.id}" data-entityName="${client.name}" style="display:${userPermissions().style};">
                            <i class="fa-solid fa-trash"></i>
                        </button>
                    </td>
                `
                table.appendChild(row)
                drawTagsIntoTables()
            }
        }

        this.register()
        //this.import()
        this.export()
        this.edit(this.entityDialogContainer, data)
        this.remove()
        //this.changeWeaponPassword()
    }

    public searchEntity = async (tableBody: InterfaceElement/*, data: any*/) => {
        const search: InterfaceElement = document.getElementById('search')
        const btnSearch: InterfaceElement = document.getElementById('btnSearch')
        search.value = infoPage.search
        await search.addEventListener('keyup', async () => {
            /********const arrayData: any = await data.filter((user: any) =>
                `${user.id}
                ${user.firstName}
                 ${user.lastName}
                 ${user.username}`
                    .toLowerCase()
                    .includes(search.value.toLowerCase())
            )

            let filteredResult = arrayData.length
            let result = arrayData
            if (filteredResult >= tableRows) filteredResult = tableRows

            this.load(tableBody, currentPage, result)

            this.pagination(result, tableRows, currentPage)*/

        })
        btnSearch.addEventListener('click', async () => {
            new Crews().render(Config.offset , Config.currentPage, search.value.toLowerCase().trim())
        })
    }

    private register() {
        // register entity
        const openEditor: InterfaceElement = document.getElementById('new-entity')
        openEditor.addEventListener('click', (): void => {
            renderInterface('Crew')
        })

        const renderInterface = async (entities: string): Promise<void> => {
            this.entityDialogContainer.innerHTML = '' //style="max-width:90%"
            this.entityDialogContainer.style.display = 'flex'
            this.entityDialogContainer.innerHTML = `
                <div class="entity_editor" id="entity-editor">
                <div class="entity_editor_header">
                    <div class="user_info">
                    <div class="avatar"><i class="fa-regular fa-users"></i></div>
                    <h1 class="entity_editor_title">Registrar <br><small>Patrulla</small></h1>
                    </div>

                    <button class="btn btn_close_editor" id="close"><i class="fa-regular fa-x"></i></button>
                </div>

                <!-- EDITOR BODY -->
                <div class="entity_editor_body">

                    <div class="material_input">
                    <input type="text" id="entity-name" autocomplete="none">
                    <label for="entity-name"><i class="fa-solid fa-gun"></i> Nombre</label>
                    </div>

                    <div class="material_input">
                    <input type="text" id="entity-vehicle" autocomplete="none" readonly>
                    <label for="entity-vehicule"><i class="fa-solid fa-car" readonly></i> Vehículo</label>
                    </div>

                    <div class="material_input">
                    <input type="text" id="entity-supervisor" autocomplete="none" readonly>
                    <label for="entity-supervisor"><i class="fa-solid fa-person-military-pointing"></i> Supervisor</label>
                    </div>

                    <div class="material_input_select">
                    <label for="entity-state">Estado</label>
                    <input type="text" id="entity-state" class="input_select" readonly placeholder="cargando..." autocomplete="none">
                    <div id="input-options" class="input_options">
                    </div>
                    </div>

                </div>
                <!-- END EDITOR BODY -->
                    
                <div class="entity_editor_footer">
                    <button class="btn btn_primary btn_widder" id="register-entity">Guardar</button>
                </div>
                </div>
            `

            inputObserver()
            //inputSelect('Citadel', 'entity-citadel')
            //inputSelect('Crew', 'entity-customer')
            this.selectVehicle()
            this.selectUser()
            inputSelect('WeaponState', 'entity-state', 'Disponible')
            //inputSelect('Department', 'entity-department')
            //inputSelect('Business', 'entity-business')
            this.close()

            const registerButton: InterfaceElement = document.getElementById('register-entity')
            registerButton.addEventListener('click', async() => {
                const inputsCollection: any = {
                    name: document.getElementById('entity-name'),
                    plate: document.getElementById('entity-plate'),
                    serie: document.getElementById('entity-serie'),
                    state: document.getElementById('entity-state')
                }

                const raw = JSON.stringify({
                    "name": `${inputsCollection.name.value}`,
                    "licensePlate": `${inputsCollection.plate.value}`,
                    "nroSerie": `${inputsCollection.serie.value}`,
                    "weaponState": {
                        "id": `${inputsCollection.state.dataset.optionid}`
                    },
                    "business":{
                        "id": `${businessId}`
                    },
                    'creationDate': `${currentDateTime().date}`,
                    'creationTime': `${currentDateTime().time}`,
                })
                if(inputsCollection.name.value === '' || inputsCollection.name.value === undefined){
                    alert("¡Nombre vacío!")
                }else if(inputsCollection.plate.value === '' || inputsCollection.plate.value === undefined){
                    alert("¡Placa vacía!")
                }else{
                    reg(raw)
                }
            })

        }

        const reg = async (raw: any) => {
            registerEntity(raw, 'Crew')
                .then((res) => {
                    setTimeout(async () => {
                        //let data = await getWeapons()
                        let parse = JSON.parse(raw);
                        eventLog('INS', 'PATRULLA', `${parse.name}`, '')
                        const tableBody: InterfaceElement = document.getElementById('datatable-body')
                        const container: InterfaceElement = document.getElementById('entity-editor-container')

                        new CloseDialog().x(container)
                        new Crews().render(Config.offset, Config.currentPage, infoPage.search)
                        //new Clients().load(tableBody, currentPage, data)
                    }, 1000)
                })
        }
    }


    private edit(container: InterfaceElement, data: Data) {
        // Edit entity
        const edit: InterfaceElement = document.querySelectorAll('#edit-entity')
        edit.forEach((edit: InterfaceElement) => {
            const entityId = edit.dataset.entityid
            edit.addEventListener('click', (): void => {
                RInterface('Crew', entityId)
            })
        })

        const RInterface = async (entities: string, entityID: string): Promise<void> => {
            const data: any = await getEntityData(entities, entityID)
            this.entityDialogContainer.innerHTML = ''
            this.entityDialogContainer.style.display = 'flex'
            this.entityDialogContainer.innerHTML = `
                <div class="entity_editor" id="entity-editor">
                <div class="entity_editor_header">
                    <div class="user_info">
                    <div class="avatar"><i class="fa-regular fa-gun"></i></div>
                    <h1 class="entity_editor_title">Editar <br><small>${data.name}</small></h1>
                    </div>

                    <button class="btn btn_close_editor" id="close"><i class="fa-solid fa-x"></i></button>
                </div>

                <!-- EDITOR BODY -->
                <div class="entity_editor_body">
                    <div class="material_input">
                    <input type="text" id="entity-name" class="input_filled" value="${data.name}" readonly>
                    <label for="entity-name">Nombre</label>
                    </div>

                    <div class="material_input">
                    <input type="text" id="entity-plate" class="input_filled" value="${data.licensePlate}" readonly>
                    <label for="entity-plate">Placa</label>
                    </div>

                    <div class="material_input">
                    <input type="text" id="entity-serie" class="input_filled" value="${data.nroSerie}">
                    <label for="entity-serie">Serie</label>
                    </div>

                    <div class="material_input_select">
                    <label for="entity-state">Estado</label>
                    <input type="text" id="entity-state" class="input_select" readonly placeholder="cargando...">
                    <div id="input-options" class="input_options">
                    </div>
                    </div>

                    <div class="input_detail">
                        <label for="creation-date"><i class="fa-solid fa-calendar"></i></label>
                        <input type="date" id="creation-date" class="input_filled" value="${data.creationDate}" readonly>
                    </div>
                    <br>
                    <div class="input_detail">
                        <label for="creation-time"><i class="fa-solid fa-clock"></i></label>
                        <input type="time" id="creation-time" class="input_filled" value="${data.creationTime}" readonly>
                    </div>
                    <br>
                    <div class="input_detail">
                        <label for="log-user"><i class="fa-solid fa-user"></i></label>
                        <input type="text" id="log-user" class="input_filled"value="${data.createdBy}" readonly>
                    </div>

                </div>
                <!-- END EDITOR BODY -->

                <div class="entity_editor_footer">
                    <button class="btn btn_primary btn_widder" id="update-changes" style="display:${userPermissions().style};">Guardar</button>
                </div>
                </div>
            `

            inputObserver()
            //inputSelect('Business', 'entity-citadel')
            //inputSelect('Crew', 'entity-customer')
            inputSelect('WeaponState', 'entity-state', data.weaponState.name)
            //inputSelect('Department', 'entity-department')
            //inputSelect('Business', 'entity-business')
            this.close()
            UUpdate(entityID, data.name)
        }

        const UUpdate = async (entityId: any, user: any): Promise<void> => {
            const updateButton: InterfaceElement =
                document.getElementById('update-changes')
            updateButton.addEventListener('click', () => {
                const $value = {
                    // @ts-ignore
                    name: document.getElementById('entity-name'),
                    // @ts-ignore
                    plate: document.getElementById('entity-plate'),
                    // @ts-ignore
                    serie: document.getElementById('entity-serie'),
                    // @ts-ignore
                    status: document.getElementById('entity-state'),
                }
                let raw = JSON.stringify({
                    // @ts-ignore
                    "name": `${$value.name?.value}`,
                    // @ts-ignore
                    "plate": `${$value.plate?.value}`,
                    // @ts-ignore
                    "nroSerie": `${$value.serie?.value}`,
                    // @ts-ignore
                    "weaponState": {
                        "id": `${$value.status?.dataset.optionid}`
                    }
                })
                // @ts-ignore
                if ($value.name.value === '' || $value.name.value === undefined) {
                    alert("Nombre vacío!");
                }
                // @ts-ignore
                else if ($value.plate.value === '' || $value.plate.value === undefined) {
                    alert("Placa vacía!");
                }else{
                    update(raw)
                }
            })
            const update = (raw: any) => {
                updateEntity('Crew', entityId, raw)
                    .then((res) => {
                        setTimeout(async () => {
                            let tableBody: InterfaceElement
                            let container: InterfaceElement
                            let data: any
                            
                            //data = await getWeapons()
                            eventLog('UPD', 'PATRULLA', `${user}`, '')
                            new CloseDialog()
                                .x(container =
                                    document.getElementById('entity-editor-container')
                                )
                            new Crews().render(infoPage.offset, infoPage.currentPage, infoPage.search)
                           /* new Clients().load(tableBody
                                = document.getElementById('datatable-body'),
                                currentPage,
                                data
                            )*/

                        }, 100)
                    })
            }
        }
    }

    private remove() {
        const remove: InterfaceElement = document.querySelectorAll('#remove-entity')
        remove.forEach((remove: InterfaceElement) => {

            const entityId = remove.dataset.entityid
            const entityName = remove.dataset.entityname
            // BOOKMARK: MODAL
            remove.addEventListener('click', (): void => {
                this.dialogContainer.style.display = 'block'
                this.dialogContainer.innerHTML = `
                    <div class="dialog_content" id="dialog-content">
                        <div class="dialog dialog_danger">
                        <div class="dialog_container">
                            <div class="dialog_header">
                            <h2>¿Deseas eliminar esta arma?</h2>
                            </div>

                            <div class="dialog_message">
                            <p>Esta acción no se puede revertir</p>
                            </div>

                            <div class="dialog_footer">
                            <button class="btn btn_primary" id="cancel">Cancelar</button>
                            <button class="btn btn_danger" id="delete">Eliminar</button>
                            </div>
                        </div>
                        </div>
                    </div>`

                const deleteButton: InterfaceElement = document.getElementById('delete')
                const cancelButton: InterfaceElement = document.getElementById('cancel')
                const dialogContent: InterfaceElement = document.getElementById('dialog-content')

                deleteButton.onclick = () => {
                    deleteEntity('Crew', entityId)
                    .then((res) => {
                        setTimeout(async () => {
                            //let data = await getWeapons();
                            eventLog('DLT', 'PATRULLA', `${entityName}`, '')
                            const tableBody = document.getElementById('datatable-body');
                            new CloseDialog().x(dialogContent);
                            new Crews().render(infoPage.offset, infoPage.currentPage, infoPage.search)
                            //new Clients().load(tableBody, currentPage, data);
                        }, 1000);
                    })
                }

                cancelButton.onclick = () => {
                    new CloseDialog().x(dialogContent)
                    //this.render()
                }
            })
        })

    }

    private export = (): void => {
        const exportWeapons: InterfaceElement = document.getElementById('export-entities');
        exportWeapons.addEventListener('click', async() => {
            this.dialogContainer.style.display = 'block';
            this.dialogContainer.innerHTML = `
                <div class="dialog_content" id="dialog-content">
                    <div class="dialog">
                        <div class="dialog_container padding_8">
                            <div class="dialog_header">
                                <h2>Seleccione un tipo</h2>
                            </div>

                            <div class="dialog_message padding_8">
                                <div class="form_group">
                                    <label for="exportCsv">
                                        <input type="radio" id="exportCsv" name="exportOption" value="csv" /> CSV
                                    </label>

                                    <label for="exportXls">
                                        <input type="radio" id="exportXls" name="exportOption" value="xls" checked /> XLS
                                    </label>

                                    <label for="exportPdf">
                                        <input type="radio" id="exportPdf" name="exportOption" value="pdf" /> PDF
                                    </label>
                                </div>
                            </div>

                            <div class="dialog_footer">
                                <button class="btn btn_primary" id="cancel">Cancelar</button>
                                <button class="btn btn_danger" id="export-data">Exportar</button>
                            </div>
                        </div>
                    </div>
                </div>
            `;
            inputObserver();
            const _closeButton: InterfaceElement = document.getElementById('cancel');
            const exportButton: InterfaceElement = document.getElementById('export-data');
            const _dialog: InterfaceElement = document.getElementById('dialog-content');
            exportButton.addEventListener('click', async() => {
                const _values: any = {
                    exportOption: document.getElementsByName('exportOption')
                }
                let rawExport = JSON.stringify({
                    "filter": {
                        "conditions": [
                          {
                            "property": "business.id",
                            "operator": "=",
                            "value": `${businessId}`
                          },
                          {
                            "property": "userType",
                            "operator": "=",
                            "value": `GUARD`
                          },
                          {
                            "property": "isSuper",
                            "operator": "=",
                            "value": `${false}`
                          }
                        ],
                        
                    }, 
                    sort: "-createdDate",
                    fetchPlan: 'full',
                    
                })
                const users: any = await getFilterEntityData("Crew", rawExport) //await getWeapons()
                for (let i = 0; i < _values.exportOption.length; i++) {
                    let ele: any = _values.exportOption[i]
                    if (ele.type = "radio") {
    
                        if (ele.checked){
                            if(ele.value == "xls"){
                                // @ts-ignore
                                exportClientXls(users)
                            }else if(ele.value == "csv"){
                                // @ts-ignore
                                exportClientCsv(users)
                            }else if(ele.value == "pdf"){
                                // @ts-ignore
                                exportClientPdf(users)
                            }
                        }
                    }
                }
            })
            _closeButton.onclick = () => {
                new CloseDialog().x(_dialog);
            };
        });
    };

    private pagination(items: [], limitRows: number, currentPage: number) {
        const tableBody: InterfaceElement = document.getElementById('datatable-body')
        const paginationWrapper: InterfaceElement = document.getElementById('pagination-container')
        paginationWrapper.innerHTML = ''

        let pageCount: number
        pageCount = Math.ceil(infoPage.count / limitRows)

        let button: InterfaceElement

        if(pageCount <= Config.maxLimitPage){
            for (let i = 1; i < pageCount + 1; i++) {
                button = setupButtons(
                    i /*, items, currentPage, tableBody, limitRows*/
                )

                paginationWrapper.appendChild(button)
            }
            fillBtnPagination(currentPage, Config.colorPagination)
        }else{
            pagesOptions(items, currentPage)  
        }

        function setupButtons(page: any /*, items: any, currentPage: number, tableBody: InterfaceElement, limitRows: number*/) {
            const button: InterfaceElement = document.createElement('button')
            button.classList.add('pagination_button')
            button.setAttribute("name", "pagination-button")
            button.setAttribute("id", "btnPag"+page)
            button.innerText = page

            button.addEventListener('click', (): void => {
                infoPage.offset = Config.tableRows * (page - 1)
                currentPage = page
                new Crews().render(infoPage.offset, currentPage, infoPage.search)
                //new Clients().load(tableBody, page, items)
            })

            return button
        }

        function pagesOptions(items: any, currentPage: any) {
            paginationWrapper.innerHTML = ''
            let pages = pageNumbers(pageCount, Config.maxLimitPage, currentPage)
            
            const prevButton: InterfaceElement = document.createElement('button')
            prevButton.classList.add('pagination_button')
            prevButton.innerText = "<<"     
            paginationWrapper.appendChild(prevButton)

            const nextButton: InterfaceElement = document.createElement('button')
            nextButton.classList.add('pagination_button')
            nextButton.innerText = ">>"
    
            for (let i = 0; i < pages.length; i++) {
                if(pages[i] > 0 && pages[i] <= pageCount){
                    button = setupButtons(
                        pages[i]
                    )
                    paginationWrapper.appendChild(button)
                }
            }
            paginationWrapper.appendChild(nextButton)
            fillBtnPagination(currentPage, Config.colorPagination)
            setupButtonsEvents(prevButton, nextButton)
        }

        function setupButtonsEvents(prevButton: InterfaceElement, nextButton: InterfaceElement) {
            prevButton.addEventListener('click', (): void => {
                new Crews().render(Config.offset, Config.currentPage, infoPage.search)
            })

            nextButton.addEventListener('click', (): void => {
                infoPage.offset = Config.tableRows * (pageCount - 1)
                new Crews().render(infoPage.offset, pageCount, infoPage.search)
            })
        }
    }

    private close(): void {
        const closeButton: InterfaceElement = document.getElementById('close')
        const editor: InterfaceElement = document.getElementById('entity-editor-container')

        closeButton.addEventListener('click', () => {
            console.log('close')
            new CloseDialog().x(editor)
        }, false)
    }

    private selectVehicle(): void {
        
        const element: InterfaceElement = document.getElementById('entity-vehicle')
        //let offset = 0

            element.addEventListener('click', async (): Promise<void> => {
                modalTable(0, "", "CAMIONETA")
            })

            async function modalTable(offset: any, search: any, type: any){
                const dialogContainer: InterfaceElement =
                document.getElementById('app-dialogs')
                let raw = JSON.stringify({
                    "filter": {
                        "conditions": [
                          {
                            "property": "business.id",
                            "operator": "=",
                            "value": `${businessId}`
                          },
                          {
                            "property": "vehicularState.name",
                            "operator": "=",
                            "value": `Disponible`
                          },
                          {
                            "property": "type",
                            "operator": "=",
                            "value": `${type}`
                          }
                        ],
                        
                    }, 
                    sort: "-createdDate",
                    limit: Config.modalRows,
                    offset: offset,
                    fetchPlan: 'full',
                    
                })
                if(search != ""){
                    raw = JSON.stringify({
                        "filter": {
                            "conditions": [
                              {
                                "group": "OR",
                                "conditions": [
                                    {
                                    "property": "licensePlate",
                                    "operator": "contains",
                                    "value": `${search.toLowerCase()}`
                                    }
                                ]
                              },
                              {
                                "property": "business.id",
                                "operator": "=",
                                "value": `${businessId}`
                              },
                              {
                                "property": "vehicularState.name",
                                "operator": "=",
                                "value": `Disponible`
                              },
                              {
                                "property": "type",
                                "operator": "=",
                                "value": `${type}`
                              }
                            ],
                            
                        }, 
                        sort: "-createdDate",
                        limit: Config.modalRows,
                        offset: offset,
                        fetchPlan: 'full',
                        
                    })
                }
                let dataModal = await getFilterEntityData("Vehicular", raw)
                dialogContainer.style.display = 'block'
                dialogContainer.innerHTML = `
                    <div class="dialog_content" id="dialog-content">
                        <div class="dialog">
                            <div class="dialog_container padding_8">
                                <div class="dialog_header">
                                    <h2>Vehículos disponibles</h2>
                                </div>

                                <div class="dialog_message padding_8">
                                    <div class="datatable_tools">
                                        <input type="search"
                                        class="search_input"
                                        placeholder="Buscar"
                                        id="search-modal">
                                        <select id="select">
                                            <option value="CAMIONETA" selected>CAMIONETA</option>
                                            <option value="AUTO">AUTO</option>
                                            <option value="MOTO">MOTO</option>
                                            <option value="LANCHA">LANCHA</option>
                                        </select>
                                        <button
                                            class="datatable_button add_user"
                                            id="btnSearchModal">
                                            <i class="fa-solid fa-search"></i>
                                        </button>
                                    </div>
                                    <div class="dashboard_datatable">
                                        <table class="datatable_content margin_t_16">
                                        <thead>
                                            <tr>
                                            <th>Placa</th>
                                            <th>Tipo</th>
                                            <th></th>
                                            </tr>
                                        </thead>
                                        <tbody id="datatable-modal-body">
                                        </tbody>
                                        </table>
                                    </div>
                                    <br>
                                </div>

                                <div class="dialog_footer">
                                    <button class="btn btn_primary" id="prevModal"><i class="fa-solid fa-arrow-left"></i></button>
                                    <button class="btn btn_primary" id="nextModal"><i class="fa-solid fa-arrow-right"></i></button>
                                    <button class="btn btn_danger" id="cancel">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                `
                inputObserver()
                const datetableBody: InterfaceElement = document.getElementById('datatable-modal-body')
                if (dataModal.length === 0) {
                    let row: InterfaceElement = document.createElement('tr')
                    row.innerHTML = `
                        <td>No hay datos</td>
                        <td></td>
                        <td></td>
                    `
                    datetableBody.appendChild(row)
                }
                else {
                    for (let i = 0; i < dataModal.length; i++) {
                        let client = dataModal[i]
                        let row: InterfaceElement =
                            document.createElement('tr')
                        row.innerHTML += `
                            <td>${client.licensePlate}</dt>
                            <td>${client?.type ?? ''}</dt>
                            <td class="entity_options">
                                <button class="button" id="edit-entity" data-entityId="${client.id}" data-entityName="${client.licensePlate}" data-entityType="${client.type}">
                                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                                </button>
                            </td>
                        `
                        datetableBody.appendChild(row)
                        drawTagsIntoTables()
                    }
                }
                const txtSearch: InterfaceElement = document.getElementById('search-modal')
                const _selectType: InterfaceElement = document.getElementById('select')
                const btnSearchModal: InterfaceElement = document.getElementById('btnSearchModal')
                const _selectVehicle: InterfaceElement = document.querySelectorAll('#edit-entity')
                const _closeButton: InterfaceElement = document.getElementById('cancel')
                const _dialog: InterfaceElement = document.getElementById('dialog-content')
                const prevModalButton: InterfaceElement = document.getElementById('prevModal')
                const nextModalButton: InterfaceElement = document.getElementById('nextModal')

                txtSearch.value = search ?? ''
                _selectType.value = type


                _selectVehicle.forEach((edit: InterfaceElement) => {
                    const entityId = edit.dataset.entityid
                    const entityName = edit.dataset.entityname
                    const entityType = edit.dataset.entitytype
                    edit.addEventListener('click', (): void => {
                        element.setAttribute('data-optionid', entityId)
                        element.setAttribute('value', `${entityType} [${entityName}]`)
                        element.classList.add('input_filled')
                        new CloseDialog().x(_dialog)
                    })
                
                })

                btnSearchModal.onclick = () => {
                    console.log(txtSearch.value)
                    console.log(_selectType.value)
                    modalTable(0, txtSearch.value, _selectType.value)
                }

                _closeButton.onclick = () => {
                    new CloseDialog().x(_dialog)
                }

                nextModalButton.onclick = () => {
                    offset = Config.modalRows + (offset)
                    modalTable(offset, search, _selectType.value)
                }

                prevModalButton.onclick = () => {
                    offset = Config.modalRows - (offset)
                    modalTable(offset, search, _selectType.value)
                }
            }

    }

    private selectUser(): void {
        
        const supervisor: InterfaceElement = document.getElementById('entity-supervisor')


            supervisor.addEventListener('click', async (): Promise<void> => {
                modalTable(0, "", "SUPERVISOR")
            })

            async function modalTable(offset: any, search: any, type: any){
                const dialogContainer: InterfaceElement =
                document.getElementById('app-dialogs')
                let raw = JSON.stringify({
                    "filter": {
                        "conditions": [
                          {
                            "property": "business.id",
                            "operator": "=",
                            "value": `${businessId}`
                          },
                          {
                            "property": "userState.name",
                            "operator": "=",
                            "value": `Disponible`
                          },
                          {
                            "property": "userType",
                            "operator": "=",
                            "value": `GUARD`
                          }
                        ],
                        
                    }, 
                    sort: "-createdDate",
                    limit: Config.modalRows,
                    offset: offset,
                    fetchPlan: 'full',
                    
                })
                if(search != ""){
                    raw = JSON.stringify({
                        "filter": {
                            "conditions": [
                              {
                                "group": "OR",
                                "conditions": [
                                    {
                                    "property": "firstName",
                                    "operator": "contains",
                                    "value": `${search.toLowerCase()}`
                                    },
                                    {
                                    "property": "lastName",
                                    "operator": "contains",
                                    "value": `${search.toLowerCase()}`
                                    },
                                    {
                                    "property": "secondLastName",
                                    "operator": "contains",
                                    "value": `${search.toLowerCase()}`
                                    },
                                    {
                                    "property": "username",
                                    "operator": "contains",
                                    "value": `${search.toLowerCase()}`
                                    }
                                ]
                              },
                              {
                                "property": "business.id",
                                "operator": "=",
                                "value": `${businessId}`
                              },
                              {
                                "property": "userState.name",
                                "operator": "=",
                                "value": `Disponible`
                              },
                              {
                                "property": "userType",
                                "operator": "=",
                                "value": `GUARD`
                              }
                            ],
                            
                        }, 
                        sort: "-createdDate",
                        limit: Config.modalRows,
                        offset: offset,
                        fetchPlan: 'full',
                        
                    })
                }
                let dataModal = await getFilterEntityData("User", raw)
                dialogContainer.style.display = 'block'
                dialogContainer.innerHTML = `
                    <div class="dialog_content" id="dialog-content">
                        <div class="dialog">
                            <div class="dialog_container padding_8">
                                <div class="dialog_header">
                                    <h2>Guardias disponibles</h2>
                                </div>

                                <div class="dialog_message padding_8">
                                    <div class="datatable_tools">
                                        <input type="search"
                                        class="search_input"
                                        placeholder="Buscar"
                                        id="search-modal">
                                        <button
                                            class="datatable_button add_user"
                                            id="btnSearchModal">
                                            <i class="fa-solid fa-search"></i>
                                        </button>
                                    </div>
                                    <div class="dashboard_datatable">
                                        <table class="datatable_content margin_t_16">
                                        <thead>
                                            <tr>
                                            <th>Nombre</th>
                                            <th>Usuario</th>
                                            <th></th>
                                            </tr>
                                        </thead>
                                        <tbody id="datatable-modal-body">
                                        </tbody>
                                        </table>
                                    </div>
                                    <br>
                                </div>

                                <div class="dialog_footer">
                                    <button class="btn btn_primary" id="prevModal"><i class="fa-solid fa-arrow-left"></i></button>
                                    <button class="btn btn_primary" id="nextModal"><i class="fa-solid fa-arrow-right"></i></button>
                                    <button class="btn btn_danger" id="cancel">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                `
                inputObserver()
                const datetableBody: InterfaceElement = document.getElementById('datatable-modal-body')
                if (dataModal.length === 0) {
                    let row: InterfaceElement = document.createElement('tr')
                    row.innerHTML = `
                        <td>No hay datos</td>
                        <td></td>
                        <td></td>
                    `
                    datetableBody.appendChild(row)
                }
                else {
                    for (let i = 0; i < dataModal.length; i++) {
                        let client = dataModal[i]
                        let row: InterfaceElement =
                            document.createElement('tr')
                        row.innerHTML += `
                            <td>${client?.firstName ?? ''} ${client?.lastName ?? ''} ${client?.secondLastName ?? ''}</dt>
                            <td>${client?.username ?? ''}</dt>
                            <td class="entity_options">
                                <button class="button" id="edit-entity" data-entityId="${client.id}" data-entityName="${client.username}">
                                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                                </button>
                            </td>
                        `
                        datetableBody.appendChild(row)
                        drawTagsIntoTables()
                    }
                }
                const txtSearch: InterfaceElement = document.getElementById('search-modal')
                const btnSearchModal: InterfaceElement = document.getElementById('btnSearchModal')
                const _selectUser: InterfaceElement = document.querySelectorAll('#edit-entity')
                const _closeButton: InterfaceElement = document.getElementById('cancel')
                const _dialog: InterfaceElement = document.getElementById('dialog-content')
                const prevModalButton: InterfaceElement = document.getElementById('prevModal')
                const nextModalButton: InterfaceElement = document.getElementById('nextModal')

                const vehicle: InterfaceElement = supervisor
                txtSearch.value = search ?? ''


                _selectUser.forEach((edit: InterfaceElement) => {
                    const entityId = edit.dataset.entityid
                    const entityName = edit.dataset.entityname
                    edit.addEventListener('click', (): void => {
                        vehicle.setAttribute('data-optionid', entityId)
                        vehicle.setAttribute('value', `${entityName}`)
                        vehicle.classList.add('input_filled')
                        new CloseDialog().x(_dialog)
                    })
                
                })

                btnSearchModal.onclick = () => {
                    console.log(txtSearch.value)
                    modalTable(0, txtSearch.value, type)
                }

                _closeButton.onclick = () => {
                    new CloseDialog().x(_dialog)
                }

                nextModalButton.onclick = () => {
                    offset = Config.modalRows + (offset)
                    modalTable(offset, search, type)
                }

                prevModalButton.onclick = () => {
                    offset = Config.modalRows - (offset)
                    modalTable(offset, search, type)
                }
            }

    }
}