//
//  Configs.ts
//
//  Generated by Poll Castillo on 09/03/2023.
//
export const Config = {
    tableRows: 50,
    currentPage: 1,
    maxLimitPage: 10,
    isSuperUser: false,
    colorPagination: "rgba(112, 111, 142, 0.16)"
}