//
//  DashboardDailySection.ts
//
//  Generated by Poll Castillo on 23/02/2023.
//
import { createChartContext } from "./CreateChartContext.js"
import { getFilterEntityData, getEntityData, getUserInfo } from "../../endpoints.js"

export const renderDailyChart = async (): Promise<void> => {
  createChartContext('daily')
  const chart = document.getElementById('daily-chart')
  const _date = new Date()
  // DATE
  const _day: number = _date.getDate()
  const _month: number = _date.getMonth() + 1
  const _year: number = _date.getFullYear()
  const date: string = `${_year}-${('0' + _month).slice(-2)}-${('0' + _day).slice(-2)}`
  
  let _userInfo: any = await getUserInfo()
  let currentUserInfo = await getEntityData('User', `${_userInfo.attributes.id}`)

  let raw = JSON.stringify({
    "filter": {
        "conditions": [
          {
            "property": "customer.id",
            "operator": "=",
            "value": `${currentUserInfo.customer.id}`
          },
          {
            "property": "creationDate",
            "operator": "=",
            "value": `${date}`
          }
        ]
    }
});
let statistics = await getFilterEntityData("Statistics_", raw);
let arryVisits: any = []
let arryMarcations: any = []
for(let i = 0; i<statistics.length; i++){
  let data = statistics[i]
  arryMarcations[0] = data.totalIngressMarcation ? data.totalIngressMarcation : 0
  arryVisits[0] = ((data.totalIngressVisitGuard ? data.totalIngressVisitGuard : 0) + (data.totalIngressVisitClient ? data.totalIngressVisitClient : 0))
}
  // @ts-ignore
  new Chart(chart, {
    type: 'bar',
    data: {
      labels: ['Registros Confirmados'],
      datasets: [
        {
          label: 'Visitas',
          data: arryVisits,
          borderWidth: 1
        },
        {
          label: 'Marcaciones',
          data: arryMarcations,
          borderWidth: 1
        }
      ]
    },
    options: {
      responsive: true,
      plugins: {
        legend: {
          position: 'bottom'
        },
        title: {
          display: true,
          text: 'Registros de hoy'
        }
      },
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  })
}